[build]
  publish = "frontend/dist"
  command = "npm install"
  functions = "backend/functions"

[functions]
  node_bundler = "esbuild"
  directory = "backend/functions"
  included_files = [
    "backend/models/**",
    "backend/routes/**",
    "backend/routes/handlers/**",
    "backend/routes/utils/**",
    "backend/service/**",
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200